server:
  port:8080


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true
