package com.ccx.time.mapper;

import com.ccx.common.entity.DayTime;
import com.ccx.common.entity.DayTimeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DayTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int countByExample(DayTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int deleteByExample(DayTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long timeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int insert(DayTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int insertSelective(DayTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    List<DayTime> selectByExample(DayTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    DayTime selectByPrimaryKey(Long timeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DayTime record, @Param("example") DayTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DayTime record, @Param("example") DayTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DayTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_time
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DayTime record);
}