package com.ccx.time.mapper;

import com.ccx.common.entity.TotalTime;
import com.ccx.common.entity.TotalTimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TotalTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_time
     *
     * @mbggenerated
     */
    int countByExample(TotalTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_time
     *
     * @mbggenerated
     */
    int deleteByExample(TotalTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_time
     *
     * @mbggenerated
     */
    int insert(TotalTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_time
     *
     * @mbggenerated
     */
    int insertSelective(TotalTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_time
     *
     * @mbggenerated
     */
    List<TotalTime> selectByExample(TotalTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_time
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TotalTime record, @Param("example") TotalTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total_time
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TotalTime record, @Param("example") TotalTimeExample example);
}